name: Pipeline

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Production Build

    steps:
      - name: Set Up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Debug Environment
        run: |
          echo "Current directory: $(pwd)"
          ls -la

      - name: Build Linux Binary
        run: |
          mkdir -p builds
          GOOS=linux GOARCH=amd64 go build -o builds/toolchain-go-linux main.go
          echo "Linux binary build success"

      - name: Build Windows Binary
        run: |
          mkdir -p builds
          GOOS=windows GOARCH=amd64 go build -o builds/toolchain-go.exe main.go
          echo "Windows binary build success:"

      - name: Verify Built Files
        run: |
          echo "Verifying builds directory content:"
          ls -la builds

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: ./builds/
