name: Pipeline

on:
  push:
    branches:
      - release/production
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Windows and Linux Binaries

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Install Dependencies
        run: go mod tidy

      - name: Build Linux Binary
        run: |
          mkdir -p builds
          GOOS=linux GOARCH=amd64 go build -o builds/toolchain-go main.go

      - name: Build Windows Binary
        run: |
          mkdir -p builds
          GOOS=windows GOARCH=amd64 go build -o builds/toolchain-go.exe main.go

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: ./builds/
