name: Pipeline
on:
  push:
    branches:
      - release/production
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Test

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Install Dependencies
        run: go mod tidy

      - name: Build Linux Binary
        run: |
          mkdir -p builds
          GOOS=linux GOARCH=amd64 go build -o builds/toolchain-go-linux main.go
          echo "Linux build success"
          ls -la builds

      - name: Build Windows Binary
        run: |
          mkdir -p builds
          GOOS=windows GOARCH=amd64 go build -o builds/toolchain-go.exe main.go
          echo "Windows binary build success"

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: builds
          path: ./builds/

      - name: Build Status
        if: success()
        run: echo "Build success"
